apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
namespace: api-service

commonLabels:
  app: mnist-api

resources:
- deployment.yaml
- service.yaml
- training-job.yaml

