apiVersion: v1
kind: Service
metadata:
  name: mnist-classifier-svc
  labels:  
    app: mnist-classifier
spec:
  type: LoadBalancer
  selector:  
    app: mnist-classifier
  ports:
  - port: 80  
    targetPort: 5000  
    protocol: TCP