apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-train-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: mnist-classifier-trainig
        image: ghcr.io/kimnjang/mnist_classifier_training:427ea31f
        args: ["--epochs", "1"]

      restartPolicy: Never