apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-train-job
spec:
  ttlSecondsAfterFinished: 180
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-pool
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: training-container
          image: ghcr.io/kimnjang/train-mnist:0.0.1
          command:
            - "python"
            - "/src/train.py"

      restartPolicy: Never