apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/kimnjang/mnist_classifier_bento
  newTag: 7e1fc0cf
- name: ghcr.io/kimnjang/mnist_classifier_training
  newTag: 7e1fc0cf

patches:
- path: training-job-patch.json
  target:
    group: batch
    kind: Job
    name: mnist-train-job
    version: v1
