apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/kimnjang/mnist_classifier_bento
  newTag: 0.4.3
- name: ghcr.io/kimnjang/mnist_classifier_training
  newTag: "23"
- name: ghcr.io/kimnjang/train-mnist
  newTag: 0.4.4

patches:
- path: training-job-patch.json
  target:
    group: batch
    kind: Job
    name: mnist-train-job
    version: v1
