apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/kimnjang/mnist_classifier_bento
  newTag: 0.3.0

patches:
- path: training-job-patch.json
  target:
    group: batch
    version: v1
    kind: Job
    name: mnist-train-job