# This is a basic workflow to help you get started with Actions

name: Package Trigger Test

# Controls when the workflow will run
on:
  registry_package:
    types: [updated]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ github.event.registry_package.package.name }}
