name: Build Training Image

on:
  workflow_dispatch:
    inputs:
      units:
        description: 'units'     
        required: true
      optimizer:
        description: 'optimizer'     
        required: true
      version:
        description: 'version'     
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Update Version & Set best hyper parameter
      run: |
        cd kustomize/overlays/dev
        kustomize edit set image ghcr.io/kimnjang/train-mnist:${{ github.event.inputs.version }}
        echo $(jq '.[].value = ["--deploy", "True", "--optimizer", "${{ github.event.inputs.optimizer }}", "--units", "${{ github.event.inputs.units }}"]' training-job-patch.json) > training-job-patch.json
        git config --global user.name ${{ github.repository_owner }}
        git config --global user.email "iam@junil.kim"
        git commit -am 'Publish new version v${{ github.event.inputs.version }} to dev'
        git push || echo 'no changes'
